#!/bin/bash 
cd $(cd $(dirname $0); pwd)
RED='\033[0;31m'
SMAY='\033[0;36m' 
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'
Version=`lsb_release -rs | cut -f1 -d"."`
mkdir LHB;cd LHB ;rm -rf JSON.lua;rm -rf locks.lua; rm -rif Script.lua;rm -rif Run.lua;rm -rif functions.lua;wget https://raw.githubusercontent.com/r00t94/z/main/Run.lua ;wget https://raw.githubusercontent.com/r00t94/z/main/locks.lua;wget https://raw.githubusercontent.com/r00t94/ws/main/salem/JSON.lua;wget https://raw.githubusercontent.com/r00t94/z/main/functions.lua;wget https://raw.githubusercontent.com/r00t94/z/main/Script.lua;cd ..

rm -rf libs;mkdir libs;cd libs;wget https://raw.githubusercontent.com/r00t94/k/main/lib/json.lua ;wget https://raw.githubusercontent.com/r00t94/k/main/lib/url.lua;wget https://raw.githubusercontent.com/r00t94/k/main/lib/redis.lua;cd ..
clear

if [ ! -f "./TG" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Not Dwonload TG .
¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source ${CNIL} . \n
\n\n"
chmod +x ./ins
./ins
exit;
fi


if [ ! -f "./LHB/Token.txt" ]; then
echo -e "${RED}
¦
¦ CAUTION:${WHITB} Your Token Bot Not Found .
¦ NOW I Run File ${SMAY}./RUN.lua${WHITB} To Enter Data For You Bot${CNIL}. \n
\n\n"
lua ./LHB/Run.lua
exit;
else
TOKEN=`cat ./LHB/Token.txt`
BOTID=`echo $TOKEN | cut -f1 -d":"`
Sudo=$(redis-cli get ${BOTID}:SUDO_ID:)
if [[ $Sudo == "" ]]; then
rm -fr ./LHB/Token.txt
lua ./LHB/Run.lua
exit;
fi
fi

UserBot=$(redis-cli get ${BOTID}:UserNameBot:)

echo "$Sudo"
echo "$UserBot"

chmod +x ./TG  

python3 -m ./scdlbot/scdlbot

if [ "$1" == "R" ]; then
while true; do
sleep 1s
rm -fr ./lhb
sudo rm -fr ~/.telegram-cli
./TG -s ./LHB/Run.lua --bot=$TOKEN
done
else 
if ! screen -list | grep -q "$UserBot"; then
screen -S "$UserBot" ./run R
else
screen -X -S "$UserBot" quit
screen -S "$UserBot" ./run R
fi
fi
